// Package recovery generates reversal SQL from indexed binlog events.
// It reads events via the query engine and emits a transaction-wrapped SQL
// script that undoes each event in reverse chronological order.
package recovery

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/bintrail/bintrail/internal/metadata"
	"github.com/bintrail/bintrail/internal/parser"
	"github.com/bintrail/bintrail/internal/query"
)

// Generator produces reversal SQL from indexed binlog events.
type Generator struct {
	db       *sql.DB
	resolver *metadata.Resolver // may be nil; triggers all-columns WHERE fallback
}

// New creates a Generator. resolver may be nil — in that case, WHERE clauses
// for UPDATE and DELETE reversals will use ALL row columns instead of just PKs.
func New(db *sql.DB, resolver *metadata.Resolver) *Generator {
	return &Generator{db: db, resolver: resolver}
}

// GenerateSQL fetches events matching opts, reverses their order (most-recent
// first), and writes a BEGIN/COMMIT-wrapped SQL script to w.
// Returns the number of SQL statements written (errors within a statement are
// emitted as SQL comments rather than halting generation).
func (g *Generator) GenerateSQL(ctx context.Context, opts query.Options, w io.Writer) (int, error) {
	rows, err := query.New(g.db).Fetch(ctx, opts)
	if err != nil {
		return 0, fmt.Errorf("failed to fetch events: %w", err)
	}
	return g.GenerateSQLFromRows(rows, w)
}

// GenerateSQLFromRows generates reversal SQL from pre-fetched rows. Use this
// when rows have already been fetched and merged from multiple sources (e.g.
// live MySQL + Parquet archives). The rows are reversed so the most-recent
// event is undone first.
func (g *Generator) GenerateSQLFromRows(rows []query.ResultRow, w io.Writer) (int, error) {
	if len(rows) == 0 {
		fmt.Fprintln(w, "-- No events matched the specified criteria.")
		return 0, nil
	}

	// Reverse so the most-recent event is undone first.
	// For multiple UPDATEs on the same row this yields the correct
	// rollback order automatically.
	slices.Reverse(rows)

	fmt.Fprintf(w, "-- Generated by bintrail recover at %s\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(w, "-- Events to reverse: %d\n", len(rows))
	fmt.Fprintln(w, "-- IMPORTANT: Review carefully before applying to production.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "BEGIN;")

	written := 0
	for _, row := range rows {
		fmt.Fprintln(w)

		gtidSuffix := ""
		if row.GTID != nil {
			gtidSuffix = " gtid=" + *row.GTID
		}
		fmt.Fprintf(w, "-- [%d] reverse %s on %s.%s pk=%s at %s%s\n",
			row.EventID,
			eventTypeName(row.EventType),
			row.SchemaName, row.TableName,
			row.PKValues,
			row.EventTimestamp.Format("2006-01-02 15:04:05"),
			gtidSuffix,
		)

		stmt, err := g.generateStatement(row)
		if err != nil {
			// Emit error as a SQL comment so the script remains runnable
			// (the transaction will roll back on first error anyway).
			fmt.Fprintf(w, "-- ERROR generating reversal for event %d: %v\n", row.EventID, err)
			continue
		}
		fmt.Fprintln(w, stmt+";")
		written++
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "COMMIT;")
	return written, nil
}

// ─── Statement generators ─────────────────────────────────────────────────────

func (g *Generator) generateStatement(row query.ResultRow) (string, error) {
	switch row.EventType {
	case parser.EventDelete:
		return g.generateInsert(row) // DELETE → INSERT (restore the deleted row)
	case parser.EventUpdate:
		return g.generateUpdate(row) // UPDATE → reverse UPDATE (restore before state)
	case parser.EventInsert:
		return g.generateDelete(row) // INSERT → DELETE (remove the inserted row)
	default:
		return "", fmt.Errorf("unknown event type %d", row.EventType)
	}
}

// generateInsert reverses a DELETE event: reconstruct the deleted row from
// row_before with a full INSERT, skipping STORED/VIRTUAL generated columns.
func (g *Generator) generateInsert(row query.ResultRow) (string, error) {
	if row.RowBefore == nil {
		return "", fmt.Errorf("row_before is nil for DELETE event (event_id=%d)", row.EventID)
	}
	genCols := g.generatedCols(row.SchemaName, row.TableName)
	var colParts, valParts []string
	for _, col := range sortedKeys(row.RowBefore) {
		if genCols[col] {
			continue
		}
		colParts = append(colParts, quoteName(col))
		valParts = append(valParts, formatValue(row.RowBefore[col]))
	}
	return fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s)",
		quoteName(row.SchemaName), quoteName(row.TableName),
		strings.Join(colParts, ", "),
		strings.Join(valParts, ", "),
	), nil
}

// generateUpdate reverses an UPDATE event: SET all columns to row_before values
// (skipping generated columns), WHERE identifies the row using row_after PK values.
func (g *Generator) generateUpdate(row query.ResultRow) (string, error) {
	if row.RowBefore == nil {
		return "", fmt.Errorf("row_before is nil for UPDATE event (event_id=%d)", row.EventID)
	}
	if row.RowAfter == nil {
		return "", fmt.Errorf("row_after is nil for UPDATE event (event_id=%d)", row.EventID)
	}

	// SET clause: restore before-image values, skipping STORED/VIRTUAL generated columns.
	genCols := g.generatedCols(row.SchemaName, row.TableName)
	var setParts []string
	for _, col := range sortedKeys(row.RowBefore) {
		if genCols[col] {
			continue
		}
		setParts = append(setParts, quoteName(col)+" = "+formatValue(row.RowBefore[col]))
	}

	// WHERE uses row_after (current state), so the UPDATE finds the right row
	// even if the PK itself was changed in the original UPDATE.
	whereParts := g.pkWhereClause(row.SchemaName, row.TableName, row.RowAfter)

	return fmt.Sprintf("UPDATE %s.%s SET %s WHERE %s",
		quoteName(row.SchemaName), quoteName(row.TableName),
		strings.Join(setParts, ", "),
		strings.Join(whereParts, " AND "),
	), nil
}

// generateDelete reverses an INSERT event: delete the inserted row using its
// row_after PK values (the current DB state).
func (g *Generator) generateDelete(row query.ResultRow) (string, error) {
	if row.RowAfter == nil {
		return "", fmt.Errorf("row_after is nil for INSERT event (event_id=%d)", row.EventID)
	}
	whereParts := g.pkWhereClause(row.SchemaName, row.TableName, row.RowAfter)
	return fmt.Sprintf("DELETE FROM %s.%s WHERE %s",
		quoteName(row.SchemaName), quoteName(row.TableName),
		strings.Join(whereParts, " AND "),
	), nil
}

// generatedCols returns the set of STORED/VIRTUAL generated column names for a
// table, using the resolver. Returns nil when the resolver is absent or the
// table is not in the snapshot — callers treat nil as an empty set.
func (g *Generator) generatedCols(schema, table string) map[string]bool {
	if g.resolver == nil {
		return nil
	}
	tm, err := g.resolver.Resolve(schema, table)
	if err != nil {
		return nil
	}
	var gen map[string]bool
	for _, c := range tm.Columns {
		if c.IsGenerated {
			if gen == nil {
				gen = make(map[string]bool)
			}
			gen[c.Name] = true
		}
	}
	return gen
}

// pkWhereClause builds "pk_col = val AND ..." from the resolver snapshot.
// Falls back to ALL columns if the table cannot be resolved (e.g. table was
// dropped, or no snapshot was loaded).
func (g *Generator) pkWhereClause(schema, table string, row map[string]any) []string {
	if g.resolver != nil {
		if tm, err := g.resolver.Resolve(schema, table); err == nil {
			pkCols := tm.PKColumnMetas()
			if len(pkCols) > 0 {
				parts := make([]string, 0, len(pkCols))
				allFound := true
				for _, pk := range pkCols {
					v, ok := row[pk.Name]
					if !ok {
						allFound = false
						break
					}
					parts = append(parts, quoteName(pk.Name)+" = "+formatValue(v))
				}
				if allFound {
					return parts
				}
			}
		}
	}
	// Fallback: all columns — verbose but always uniquely identifies the row
	// (assuming the table has no duplicates, which is true for well-formed data).
	return allColsWhere(row)
}

func allColsWhere(row map[string]any) []string {
	cols := sortedKeys(row)
	parts := make([]string, len(cols))
	for i, col := range cols {
		parts[i] = quoteName(col) + " = " + formatValue(row[col])
	}
	return parts
}

// ─── Value formatting ─────────────────────────────────────────────────────────

// formatValue renders a Go value as a MySQL literal suitable for embedding in
// a generated SQL statement.
//
// After a JSON round-trip (row_before/row_after are stored as JSON and then
// json.Unmarshal'd into map[string]any), all numeric values are float64.
// Whole-number float64s are formatted as integers; fractional ones as decimals.
func formatValue(v any) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "1"
		}
		return "0"

	case float64:
		// Detect integer-valued floats (JSON round-trip converts int→float64).
		// math.Abs guard prevents int64 overflow for very large floats.
		if !math.IsInf(val, 0) && !math.IsNaN(val) &&
			val == math.Trunc(val) && math.Abs(val) < 1e15 {
			return strconv.FormatInt(int64(val), 10)
		}
		return strconv.FormatFloat(val, 'f', -1, 64)

	case string:
		return "'" + escapeString(val) + "'"

	case map[string]any:
		// MySQL JSON column: re-serialise to JSON and store as a string literal.
		b, _ := json.Marshal(val)
		return "'" + escapeString(string(b)) + "'"

	case []any:
		// JSON array column.
		b, _ := json.Marshal(val)
		return "'" + escapeString(string(b)) + "'"

	case json.RawMessage:
		return "'" + escapeString(string(val)) + "'"

	default:
		return "'" + escapeString(fmt.Sprintf("%v", val)) + "'"
	}
}

// escapeString escapes a string for safe embedding inside a MySQL single-quoted literal.
func escapeString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `'`, `\'`)
	s = strings.ReplaceAll(s, "\x00", `\0`)
	return s
}

// quoteName wraps a MySQL identifier (schema, table, column) in backticks,
// escaping any backticks in the name itself.
func quoteName(name string) string {
	return "`" + strings.ReplaceAll(name, "`", "``") + "`"
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func eventTypeName(et parser.EventType) string {
	switch et {
	case parser.EventInsert:
		return "INSERT"
	case parser.EventUpdate:
		return "UPDATE"
	case parser.EventDelete:
		return "DELETE"
	default:
		return "UNKNOWN"
	}
}
