-- DuckDB views over a bintrail archive layout.
-- Generated by bintrail v0.50.0 at 2026-05-01T12:00:00Z.
--
-- THIS FILE IS A SNAPSHOT OF THE LAYOUT, NOT A LIVE BINDING. The globs below
-- keep picking up newly rotated partitions on their own, but the baseline
-- state views point at ONE snapshot. Re-run `bintrail views` (or download the
-- file again from the console) after taking or refreshing a baseline, and
-- whenever archive sources are added or removed.
--
-- Nothing here writes: every view is a read over Parquet files you already own.
--
-- Archive sources (an archive registered with both a local path and an S3
-- location is listed by its S3 location, so those reads work from another
-- machine; a local path below means the registry holds no S3 location this
-- file can use):
--   /data/archives/bintrail_id=11111111-2222-3333-4444-555555555555
--   s3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000
-- Baseline snapshot:
--   s3://my-bucket/baselines/ at 2026-04-30T03:00:00Z (4 table(s))

-- S3 setup, mirroring what bintrail's own DuckDB sessions configure.
INSTALL httpfs; LOAD httpfs;
INSTALL aws; LOAD aws;
CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1');
-- This secret lives only in this DuckDB session. Views persist in a database
-- file; secrets do not. Reopening that file later and querying S3 fails with
-- "No credentials are provided": run this file again in every session that
-- reads S3 (`.read views.sql`, or `duckdb -init views.sql your.db`).
-- Do not make it PERSISTENT: DuckDB would resolve your credential chain now
-- and store the resulting keys on disk.
-- No credentials appear in this file by design. If the credential chain is not
-- available where you run this, replace the secret above with explicit keys:
--   CREATE OR REPLACE SECRET bintrail_s3_chain (
--     TYPE s3, KEY_ID '…', SECRET '…', REGION '…');

-- events: every archived binlog event, across all archive sources.
--
-- union_by_name is required, not cosmetic: archives written before a column
-- existed simply lack it, and those files must read back with NULLs rather
-- than failing the whole scan. A column absent from EVERY archived file is
-- still an error — drop it from the SELECT if you hit that on an old archive.
CREATE OR REPLACE VIEW "events" AS
  SELECT
    "bintrail_id", "event_date", "event_hour",
    "event_id",
    "binlog_file",
    "start_pos",
    "end_pos",
    "event_timestamp",
    "gtid",
    "connection_id",
    "schema_name",
    "table_name",
    "event_type" AS "event_type_code",
    CASE "event_type"
      WHEN 1 THEN 'INSERT'
      WHEN 2 THEN 'UPDATE'
      WHEN 3 THEN 'DELETE'
      ELSE CAST("event_type" AS VARCHAR)
    END AS "event_type",
    "pk_values",
    "changed_columns",
    "row_before",
    "row_after",
    "schema_version",
    "query_text",
    "query_hash",
    "commit_ts_us",
    CASE WHEN "commit_ts_us" IS NULL THEN NULL
         ELSE make_timestamp(CAST("commit_ts_us" AS BIGINT)) END AS "commit_time"
  FROM read_parquet(
    [
      '/data/archives/bintrail_id=11111111-2222-3333-4444-555555555555/event_date=*/event_hour=*/*.parquet',
      's3://my-bucket/archives/bintrail_id=66666666-7777-8888-9999-000000000000/event_date=*/event_hour=*/*.parquet'
    ],
    hive_partitioning = true,
    union_by_name = true
  );

-- state_<schema>_<table>: each table's full contents as of the baseline snapshot.
--
-- These are the SNAPSHOT's rows, not the table's current state: changes after
-- the snapshot live in `events` above. To materialize a later point in time,
-- use `bintrail reconstruct` — folding the deltas back onto a baseline is what
-- that command does, and it is not expressible as a view.
CREATE OR REPLACE VIEW "state_legacy_db_audit_log" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/Legacy-DB/Audit Log.parquet');
CREATE OR REPLACE VIEW "state_shop_order_items" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop/order_items.parquet');
CREATE OR REPLACE VIEW "state_shop_orders" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop/orders.parquet');
CREATE OR REPLACE VIEW "state_shop_order_items_2" AS
  SELECT * FROM read_parquet('s3://my-bucket/baselines/2026-04-30T03-00-00Z/shop_order/items.parquet');

