#!/usr/bin/env bash
# Entrypoint for the bintrail appliance (evaluation-only).
#
# Boot order:
#   1. mysqld          (initialize datadir on first boot, then serve)
#   2. seed            (demo schema + bintrail/demo users, idempotent guard)
#   3. bintrail up     (preflight + init + stream, against this same MySQL)
#   4. bintrail shim   (loopback :3308, after the index DB exists)
#   5. proxysql        (:6033, routing SQL generated by proxysql-config)
#   6. traffic         (only after streaming is live — pre-stream changes
#                       are not indexed, `up` starts at the current binlog
#                       position)
#
# Supervision: no init system. SIGTERM/SIGINT fan out to every child;
# if ANY component dies the container exits non-zero — an evaluation
# appliance that half-works silently is worse than one that restarts.

set -euo pipefail

log() { echo "[appliance] $(date '+%H:%M:%S') $*"; }

BINTRAIL_DSN='bintrail:bintrail@tcp(127.0.0.1:3306)'
PIDS=()

shutdown() {
    log "Shutting down..."
    trap - TERM INT
    # Kill children in reverse boot order; mysqladmin gives mysqld a
    # clean shutdown (irrelevant for data — the appliance is stateless —
    # but avoids InnoDB recovery noise on quick restart cycles).
    for ((i=${#PIDS[@]}-1; i>=0; i--)); do
        kill "${PIDS[$i]}" 2>/dev/null || true
    done
    mysqladmin --protocol=tcp -h127.0.0.1 -uroot shutdown 2>/dev/null || true
    wait 2>/dev/null || true
    exit 0
}
trap shutdown TERM INT

# ── 1. MySQL ────────────────────────────────────────────────
if [ ! -d /var/lib/mysql/mysql ]; then
    log "Initializing MySQL data directory..."
    mysqld --initialize-insecure --user=mysql
fi

log "Starting mysqld..."
mysqld --user=mysql &
PIDS+=($!)

log "Waiting for MySQL..."
for _ in $(seq 1 120); do
    mysqladmin --protocol=tcp -h127.0.0.1 -uroot ping &>/dev/null && break
    sleep 1
done
mysqladmin --protocol=tcp -h127.0.0.1 -uroot ping &>/dev/null \
    || { log "MySQL did not come up"; exit 1; }

# ── 2. Seed ─────────────────────────────────────────────────
if ! mysql --protocol=tcp -h127.0.0.1 -uroot -e "SELECT 1 FROM demo.orders LIMIT 1" &>/dev/null; then
    log "Seeding demo schema and users..."
    mysql --protocol=tcp -h127.0.0.1 -uroot < /opt/bintrail/seed.sql
fi

# ── 3. bintrail up (preflight + init + stream) ──────────────
log "Starting bintrail up (stream demo schema into bintrail_index)..."
bintrail up \
    --source-dsn "${BINTRAIL_DSN}/" \
    --index-dsn  "${BINTRAIL_DSN}/bintrail_index" \
    --schemas demo \
    --server-id 99999 &
UP_PID=$!
PIDS+=($UP_PID)

# Streaming is live once stream_state has its checkpoint row (~10-15s:
# doctor + init + first checkpoint). Traffic must not start before this —
# `up` begins at the CURRENT binlog position, so earlier changes would
# never be indexed.
log "Waiting for the stream checkpoint..."
for _ in $(seq 1 120); do
    kill -0 "$UP_PID" 2>/dev/null \
        || { log "bintrail up exited during startup (see its output above)"; exit 1; }
    n=$(mysql --protocol=tcp -h127.0.0.1 -uroot -N \
        -e "SELECT COUNT(*) FROM bintrail_index.stream_state" 2>/dev/null || echo 0)
    [ "${n}" = "1" ] && break
    sleep 1
done
[ "${n:-0}" = "1" ] || { log "bintrail up never checkpointed"; exit 1; }
log "Stream is live."

# ── 4. Shim ─────────────────────────────────────────────────
log "Starting bintrail shim on 127.0.0.1:3308..."
bintrail shim \
    --listen 127.0.0.1:3308 \
    --index-dsn "${BINTRAIL_DSN}/bintrail_index" \
    --shim-config /opt/bintrail/shim.yaml &
PIDS+=($!)

for _ in $(seq 1 30); do
    (exec 3<>/dev/tcp/127.0.0.1/3308) 2>/dev/null && { exec 3>&-; break; }
    sleep 1
done
# Definitive post-loop probe (mirrors the MySQL/stream waits): without
# it, a shim that never binds (bad shim.yaml, port contention) would
# boot a half-working appliance whose time-travel queries fail with an
# opaque ProxySQL routing error at query time.
(exec 3<>/dev/tcp/127.0.0.1/3308) 2>/dev/null && exec 3>&- \
    || { log "shim never started listening on 127.0.0.1:3308"; exit 1; }

# ── 5. ProxySQL ─────────────────────────────────────────────
# Routing SQL is generated at boot (not baked at image build) so the
# hostgroups/rules always match THIS binary's proxysql-config output.
log "Generating ProxySQL routing config..."
BINTRAIL_SOURCE_DSN='demo:demo@tcp(127.0.0.1:3306)/demo' \
    bintrail proxysql-config --shim-config /opt/bintrail/shim.yaml \
    --out /tmp/proxysql-setup.sql --force

log "Starting ProxySQL on 0.0.0.0:6033..."
proxysql -f --idle-threads -c /etc/proxysql.cnf --initial &
PIDS+=($!)

for _ in $(seq 1 30); do
    (exec 3<>/dev/tcp/127.0.0.1/6032) 2>/dev/null && { exec 3>&-; break; }
    sleep 1
done
# Same post-loop probe: the mysql load below would also fail under
# set -e, but with a raw "can't connect" instead of naming the culprit.
(exec 3<>/dev/tcp/127.0.0.1/6032) 2>/dev/null && exec 3>&- \
    || { log "ProxySQL admin never came up on 127.0.0.1:6032"; exit 1; }
log "Loading routing config into ProxySQL admin..."
mysql --protocol=tcp -h127.0.0.1 -P6032 -uadmin -padmin < /tmp/proxysql-setup.sql

# ── 6. Traffic ──────────────────────────────────────────────
log "Starting traffic generator..."
traffic.sh &
PIDS+=($!)

cat <<'BANNER'

  ┌─────────────────────────────────────────────────────────────────────┐
  │  bintrail appliance is up.                                          │
  │                                                                     │
  │  Give the traffic generator ~1 minute to build history, then:      │
  │                                                                     │
  │    mysql -h 127.0.0.1 -P 6033 -u demo -pdemo demo \                 │
  │      -e "SELECT * FROM orders WHERE id = 1                          │
  │          AS OF '1 minute ago'"                                      │
  │                                                                     │
  │  Compare with the live row:                                         │
  │                                                                     │
  │    mysql -h 127.0.0.1 -P 6033 -u demo -pdemo demo \                 │
  │      -e "SELECT * FROM orders WHERE id = 1"                         │
  │                                                                     │
  │  Evaluation only — stateless: restart = fresh demo.                 │
  └─────────────────────────────────────────────────────────────────────┘

BANNER

# ── Supervise ───────────────────────────────────────────────
# If any component exits, the demo is broken — die loudly. The `|| rc=$?`
# guard matters: a child crashing non-zero would otherwise trip set -e AT
# the `wait -n` line itself, skipping the diagnostic below and exiting
# with the child's code — exactly the silent half-failure this block
# exists to prevent.
rc=0
wait -n || rc=$?
log "A component exited unexpectedly (status ${rc}); shutting the appliance down."
exit 1
