package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// ─── Parent command ───────────────────────────────────────────────────────────

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage bintrail configuration",
}

// ─── config init ──────────────────────────────────────────────────────────────

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a .bintrail.env configuration file",
	Long: `Generates a .bintrail.env file in the current directory with all available
configuration variables. Use --global to write to ~/.config/bintrail/config.env
instead.

Values already set in the environment (from the shell or an existing env file)
are written uncommented; all others are commented out as templates.

The env file is loaded automatically by all bintrail commands with precedence:
  CLI flag > environment variable > default value`,
	RunE: runConfigInit,
}

var cfgGlobal bool

func init() {
	configInitCmd.Flags().BoolVar(&cfgGlobal, "global", false, "Write to ~/.config/bintrail/config.env instead of .bintrail.env")
	configCmd.AddCommand(configInitCmd)
	rootCmd.AddCommand(configCmd)
}

func runConfigInit(cmd *cobra.Command, args []string) error {
	path := ".bintrail.env"
	if cfgGlobal {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("cannot determine home directory: %w", err)
		}
		dir := filepath.Join(home, ".config", "bintrail")
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("cannot create config directory: %w", err)
		}
		path = filepath.Join(dir, "config.env")
	}

	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("file already exists: %s\nRemove it first or edit it directly.", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("cannot check %s: %w", path, err)
	}

	content := generateEnvTemplate()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	fmt.Printf("Configuration written to %s\n", path)
	fmt.Println("Edit the file to set your values, then uncomment the lines you want to use.")
	return nil
}

// envSection groups env bindings under a section header for the template.
type envSection struct {
	Header   string
	Bindings []envTemplateEntry
}

// envTemplateEntry is a single line in the env template.
type envTemplateEntry struct {
	EnvVar      string
	Placeholder string // shown when no value is set (e.g. "user:pass@tcp(host:3306)/binlog_index")
}

// envSections defines the same env vars as envBindings (in envload.go),
// grouped by category for template generation. Keep in sync with envBindings.
var envSections = []envSection{
	{
		Header: "Database connections",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_INDEX_DSN", "user:pass@tcp(host:3306)/binlog_index"},
			{"BINTRAIL_SOURCE_DSN", "user:pass@tcp(host:3306)/myapp"},
		},
	},
	{
		Header: "Filters",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_SCHEMAS", ""},
			{"BINTRAIL_TABLES", ""},
		},
	},
	{
		Header: "Server identity",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_ID", ""},
		},
	},
	{
		Header: "Archives",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_ARCHIVE_DIR", ""},
			{"BINTRAIL_ARCHIVE_S3", "s3://my-bucket/archives/"},
			{"BINTRAIL_ARCHIVE_S3_REGION", ""},
		},
	},
	{
		Header: "S3 bucket (used by bintrail init)",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_S3_BUCKET", ""},
			{"BINTRAIL_S3_REGION", ""},
			{"BINTRAIL_S3_ARN", ""},
		},
	},
	{
		Header: "Stream settings",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_SERVER_ID", ""},
			{"BINTRAIL_BATCH_SIZE", "1000"},
			{"BINTRAIL_METRICS_ADDR", ""},
		},
	},
	{
		Header: "TLS (used by bintrail stream)",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_SSL_MODE", "preferred"},
			{"BINTRAIL_SSL_CA", ""},
			{"BINTRAIL_SSL_CERT", ""},
			{"BINTRAIL_SSL_KEY", ""},
		},
	},
	{
		Header: "Agent (used by bintrail agent)",
		Bindings: []envTemplateEntry{
			{"BINTRAIL_API_KEY", ""},
			{"BINTRAIL_AGENT_ENDPOINT", "wss://api.dbtrail.io/v1/agent"},
		},
	},
}

// generateEnvTemplate builds the .bintrail.env file content. Variables
// that are already set in the current environment are written uncommented
// with their current value; all others are commented out.
func generateEnvTemplate() string {
	var sb strings.Builder
	sb.WriteString("# Bintrail configuration\n")
	sb.WriteString("# Generated by bintrail config init\n")
	sb.WriteString("#\n")
	sb.WriteString("# Uncomment and set values below. These are loaded automatically\n")
	sb.WriteString("# by all bintrail commands. CLI flags take precedence over env vars.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Precedence: CLI flag > environment variable > default value\n")

	for _, sec := range envSections {
		fmt.Fprintf(&sb, "\n# ── %s ──\n", sec.Header)
		for _, entry := range sec.Bindings {
			if v, ok := os.LookupEnv(entry.EnvVar); ok && v != "" {
				fmt.Fprintf(&sb, "%s=%s\n", entry.EnvVar, v)
			} else if entry.Placeholder != "" {
				fmt.Fprintf(&sb, "# %s=%s\n", entry.EnvVar, entry.Placeholder)
			} else {
				fmt.Fprintf(&sb, "# %s=\n", entry.EnvVar)
			}
		}
	}

	return sb.String()
}
