package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var initShimCmd = &cobra.Command{
	Use:   "init-shim",
	Short: "Generate a shim.yaml from local .bintrail.env",
	Long: `Generates a starter shim.yaml for the dbtrail-shim binary, which serves
BYOS time-travel SQL by intercepting _flashback / _diff / _snapshot virtual
schemas via ProxySQL and answering them from the local bintrail agent.

Reads BINTRAIL_SOURCE_DSN, BINTRAIL_SERVER_ID, and BINTRAIL_API_KEY from
.bintrail.env (or the environment) to populate the tenant block. The
mysql_user / mysql_pass_sha1 credentials ProxySQL uses to authenticate
your application are emitted as TODO comments — fill them in by hand.

Use --out - to write to stdout instead of a file.`,
	RunE: runInitShim,
}

var (
	isOut      string
	isListen   string
	isAgentURL string
)

func init() {
	initShimCmd.Flags().StringVar(&isOut, "out", "shim.yaml", "Output path for the generated shim config (use - for stdout)")
	initShimCmd.Flags().StringVar(&isListen, "listen", ":3308", "Listen address for the shim's MySQL protocol port")
	initShimCmd.Flags().StringVar(&isAgentURL, "agent-url", "http://localhost:8600", "URL of the local bintrail agent the shim will query")
	bindCommandEnv(initShimCmd)
	rootCmd.AddCommand(initShimCmd)
}

func runInitShim(cmd *cobra.Command, args []string) error {
	sourceDSN := os.Getenv("BINTRAIL_SOURCE_DSN")
	serverID := os.Getenv("BINTRAIL_SERVER_ID")
	apiKey := os.Getenv("BINTRAIL_API_KEY")

	var missing []string
	if sourceDSN == "" {
		missing = append(missing, "BINTRAIL_SOURCE_DSN")
	}
	if serverID == "" {
		missing = append(missing, "BINTRAIL_SERVER_ID")
	}
	if apiKey == "" {
		missing = append(missing, "BINTRAIL_API_KEY")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required env var(s): %s\nRun 'bintrail config init' to scaffold .bintrail.env, then set these values.", strings.Join(missing, ", "))
	}

	// YAML single-quoted scalars cannot contain literal newlines; reject
	// rather than silently emit a malformed file.
	for _, v := range []struct{ name, val string }{
		{"BINTRAIL_SOURCE_DSN", sourceDSN},
		{"BINTRAIL_SERVER_ID", serverID},
		{"BINTRAIL_API_KEY", apiKey},
	} {
		if strings.ContainsAny(v.val, "\r\n") {
			return fmt.Errorf("%s contains a newline character; remove it before generating shim.yaml", v.name)
		}
	}

	content := generateShimYAML(sourceDSN, serverID, apiKey, isListen, isAgentURL)

	if isOut == "-" {
		_, err := io.WriteString(os.Stdout, content)
		return err
	}

	if _, err := os.Stat(isOut); err == nil {
		return fmt.Errorf("file already exists: %s\nRemove it first or edit it directly.", isOut)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("cannot check %s: %w", isOut, err)
	}

	if err := os.WriteFile(isOut, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", isOut, err)
	}

	fmt.Printf("Shim configuration written to %s\n", isOut)
	fmt.Println("Edit the file to fill in mysql_user and mysql_pass_sha1 before starting dbtrail-shim.")
	return nil
}

func generateShimYAML(sourceDSN, serverID, agentToken, listen, agentURL string) string {
	var sb strings.Builder
	sb.WriteString("# Bintrail BYOS time-travel SQL — shim configuration\n")
	sb.WriteString("# Generated by bintrail init-shim. See docs/byos-time-travel-sql.md.\n")
	sb.WriteString("#\n")
	sb.WriteString("# Fill in mysql_user and mysql_pass_sha1 below — these are the\n")
	sb.WriteString("# credentials ProxySQL will use to authenticate your application.\n")
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "listen: %s\n", yamlQuote(listen))
	sb.WriteString("\n")
	sb.WriteString("tenants:\n")
	fmt.Fprintf(&sb, "  - server_id: %s\n", yamlQuote(serverID))
	fmt.Fprintf(&sb, "    source_dsn: %s\n", yamlQuote(sourceDSN))
	fmt.Fprintf(&sb, "    agent_url: %s\n", yamlQuote(agentURL))
	fmt.Fprintf(&sb, "    agent_token: %s\n", yamlQuote(agentToken))
	sb.WriteString("    # TODO: fill in your application's MySQL credentials\n")
	sb.WriteString("    # mysql_user: app_user\n")
	sb.WriteString("    # TODO: SHA1 hex of mysql_user's password\n")
	sb.WriteString("    # See https://proxysql.com/documentation/users/\n")
	sb.WriteString("    # mysql_pass_sha1:\n")
	return sb.String()
}

// yamlQuote wraps s as a YAML single-quoted scalar, doubling any embedded
// single quotes per the YAML 1.2 spec. Single-quoted scalars treat all
// other characters literally — no escape processing — so this safely
// handles values containing ':', '#', '{', '[', leading whitespace, and
// other YAML-syntactic characters that would otherwise need quoting.
func yamlQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
