package views

import (
	"strings"
	"testing"

	"github.com/dbtrail/dbtrail/internal/storage"
)

// TestGenerate_customEndpointInPreamble (#1454): a file generated by a process
// that reads an S3-compatible store must say so, or the reader's DuckDB sends
// every s3:// path to AWS. The endpoint is a location, not a credential, and
// the no-credentials property of the file is unchanged.
func TestGenerate_customEndpointInPreamble(t *testing.T) {
	in := goldenInput()
	in.S3Endpoint = storage.S3Endpoint{URL: "http://minio:9000", PathStyle: true}
	out := Generate(in)

	for _, want := range []string{
		"CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1', ENDPOINT 'minio:9000', URL_STYLE 'path', USE_SSL false);",
		"-- s3:// paths here live in an S3-compatible store at http://minio:9000, not in AWS.",
		"--     ENDPOINT 'minio:9000', URL_STYLE 'path', USE_SSL false);",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q:\n%s", want, out)
		}
	}
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			continue
		}
		if strings.Contains(line, "KEY_ID '") || strings.Contains(line, "testdummy") {
			t.Errorf("executable line carries a credential: %s", line)
		}
	}
}

// The zero endpoint changes nothing: the golden file (AWS) stays byte-identical.
func TestGenerate_noEndpointIsAWS(t *testing.T) {
	out := Generate(goldenInput())
	if strings.Contains(out, "ENDPOINT") || strings.Contains(out, "S3-compatible") {
		t.Errorf("an AWS layout mentions an endpoint:\n%s", out)
	}
}
