package views

import (
	"strings"
	"testing"

	"github.com/dbtrail/dbtrail/internal/duckdbutil"
	"github.com/dbtrail/dbtrail/internal/storage"
)

// TestGenerate_customEndpointInPreamble (#1454): a file generated by a process
// that reads an S3-compatible store must say so, or the reader's DuckDB sends
// every s3:// path to AWS. The endpoint is a location, not a credential, and
// the no-credentials property of the file is unchanged.
//
// The routing half asserts against duckdbutil.S3SettingStatements rather than a
// list of literals. The literal version could not see the defect it was written
// to catch: it enumerated the three statements the file happened to emit, so
// when the file's copy of the list lost s3_region, the test agreed with the
// copy. Deriving from the shared renderer means a settings that the process
// applies and the file omits fails here.
func TestGenerate_customEndpointInPreamble(t *testing.T) {
	in := goldenInput()
	in.S3Endpoint = storage.S3Endpoint{URL: "http://minio:9000", PathStyle: true}
	out := Generate(in)

	// Outside the secret as well: an interactive DuckDB continues past a failed
	// statement, so a session whose credential chain resolves nothing would
	// skip the secret and read AWS. GLOBAL because a plain SET binds to one
	// connection.
	// Pins THIS FIXTURE, so the loop below cannot go vacuous when the shared
	// list shrinks. It says nothing about any producer: only `bintrail views
	// --region` ever fills ArchiveRegion, and the console leaves it empty, so
	// a console-generated file pins no region at all and relies on the
	// reader's own resolution (see #1462).
	routing := duckdbutil.S3SettingStatements(in.ArchiveRegion, in.S3Endpoint)
	if len(routing) < 4 {
		t.Fatalf("fixture exercises only %d settings; it must cover the region too: %v", len(routing), routing)
	}
	for _, stmt := range routing {
		if !strings.Contains(out, stmt+";") {
			t.Errorf("the process applies %q but the file does not:\n%s", stmt, out)
		}
	}

	for _, want := range []string{
		"CREATE OR REPLACE SECRET bintrail_s3_chain (TYPE s3, PROVIDER credential_chain, REGION 'us-east-1', ENDPOINT 'minio:9000', URL_STYLE 'path', USE_SSL false);",
		"-- s3:// paths here live in an S3-compatible store at http://minio:9000, not in AWS.",
		"--     ENDPOINT 'minio:9000', URL_STYLE 'path', USE_SSL false);",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q:\n%s", want, out)
		}
	}
	// The routing must precede the secret: a failed CREATE SECRET must not
	// leave the session unrouted for the statements that follow.
	if strings.Index(out, "SET GLOBAL s3_endpoint=") > strings.Index(out, "CREATE OR REPLACE SECRET") {
		t.Errorf("routing is emitted after the secret:\n%s", out)
	}
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			continue
		}
		if strings.Contains(line, "KEY_ID '") || strings.Contains(line, "testdummy") {
			t.Errorf("executable line carries a credential: %s", line)
		}
	}
}

// The zero endpoint changes nothing: the golden file (AWS) stays byte-identical.
func TestGenerate_noEndpointIsAWS(t *testing.T) {
	out := Generate(goldenInput())
	if strings.Contains(out, "ENDPOINT") || strings.Contains(out, "S3-compatible") || strings.Contains(out, "SET GLOBAL") {
		t.Errorf("an AWS layout mentions an endpoint or reroutes httpfs:\n%s", out)
	}
}

// A reader who sees no REGION clause cannot tell "nothing to pin" from "we
// could not agree", and the two need different action from them: the second
// means one of their buckets will answer 301 and the file needs splitting.
func TestGenerate_ambiguousRegionSaysSo(t *testing.T) {
	in := goldenInput()
	// A NON-EMPTY region with the flag set: with "" the suppression assertion
	// below passes whatever the flag does, which is a guard that cannot fail.
	in.ArchiveRegion, in.RegionAmbiguous = "eu-central-1", true
	out := Generate(in)

	if !strings.Contains(out, "each detected in a DIFFERENT region") {
		t.Errorf("an ambiguous region renders silently:\n%s", out)
	}
	// Executable lines only: the file's closing comment SHOWS a sample secret
	// carrying REGION, so an unscoped scan matches prose and never fails.
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			continue
		}
		if strings.Contains(line, "REGION '") || strings.Contains(line, "s3_region") {
			t.Errorf("a region was pinned despite the buckets disagreeing: %s", line)
		}
	}
	// The note is prose, so it must not be executable.
	for _, line := range strings.Split(out, "\n") {
		if strings.Contains(line, "each detected in a DIFFERENT region") && !strings.HasPrefix(strings.TrimSpace(line), "--") {
			t.Errorf("the note is not a comment: %s", line)
		}
	}
}

// The ordinary case stays silent: a pinned region needs no explanation.
func TestGenerate_unambiguousRegionCarriesNoNote(t *testing.T) {
	in := goldenInput()
	in.ArchiveRegion, in.RegionAmbiguous = "eu-central-1", false
	out := Generate(in)
	if strings.Contains(out, "each detected in a DIFFERENT region") {
		t.Errorf("a pinned region carries the ambiguity note:\n%s", out)
	}
	if !strings.Contains(out, "REGION 'eu-central-1'") {
		t.Errorf("the pinned region is missing from the secret:\n%s", out)
	}
}
